apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  type: ClusterIP
  ports:
    - port: 8086
      targetPort: 8086
  selector:
    app: influxdb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-influxdb
  labels:
    app: influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb
spec:
  selector:
    matchLabels:
      app: influxdb
  serviceName: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: svc_influxdb
        imagePullPolicy: Never
        volumeMounts:
          - name: influxdb
            mountPath: /var/lib/influxdb
        ports:
        - containerPort: 8086
        livenessProbe:
          exec:
            command:
            - sh
            - /tmp/liveness.sh
      volumes:
        - name: influxdb
          persistentVolumeClaim:
            claimName: pv-influxdb
