# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    kubeconfig.yaml                                    :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: user42 <user42@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/04/11 14:56:46 by user42            #+#    #+#              #
#    Updated: 2021/04/11 14:57:10 by user42           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

