apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-mysql
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: svc_mysql
        imagePullPolicy: Never
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root
          - name: MYSQL_DATABASE
            value: wordpress
          - name: MYSQL_USER
            value: admin
          - name: MYSQL_PASS
            value: admin
        volumeMounts:
          - name: mysql
            mountPath: /var/lib/mysql
        ports:
        - containerPort: 3306
        livenessProbe:
          exec:
            command:
            - sh
            - /tmp/liveness.sh
      volumes:
        - name: mysql
          persistentVolumeClaim:
            claimName: pv-mysql
