# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    setup.sh                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: user42 <user42@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/04/05 10:17:55 by besellem          #+#    #+#              #
#    Updated: 2021/04/12 12:27:55 by user42           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# generated by figlet command
echo "\033[2J\033[H\033[1;31m\
 / _| |_     ___  ___ _ ____   _(_)
| |_| __|   / __|/ _ \ '__\ \ / / |/ __/ _ \/ __|
|  _| |_    \__ \  __/ |   \ V /| | (_|  __/\__ \\
|_|  \__|___|___/\___|_|    \_/ |_|\___\___||___/
       |_____|\
\033[0m\n"

# kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.6/manifests/namespace.yaml
# kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.6/manifests/metallb.yaml

# On first install only
# kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
# kubectl expose rc example --port=8765 --target-port=9376 --name=example-service --type=LoadBalancer

setup() {
	for contnr in 'nginx' 'mysql' 'influxdb' 'wordpress' 'phpmyadmin' 'ftps' 'grafana'
	do
		echo "Building $contnr..."
		docker build -t $contnr ./srcs/$contnr
		echo	
	done
}


if [ `uname` = Darwin ]
then
	echo "export MINIKUBE_HOME=/goinfre/$USER/"
	source ~/.zshrc
fi

# if [ `uname` = Linux ]
# then
	minikube delete
	minikube start --driver=docker
	minikube addons enable metrics-server
	minikube addons enable dashboard
	minikube addons enable metallb

	# kubectl apply -f https://raw.githubusercontent.com/google/metallb/v0.8.1/manifests/metallb.yaml
	# setup
# else
# 	echo "export MINIKUBE_HOME=/goinfre/$USER/"
# 	source ~/.zshrc
# 	echo "The project needs to be run on Linux"
# 	echo "Sorry :)"
# fi
